### PR TITLE
Adding support for multiple LHS, use data.table

### PR DESCRIPTION
**Pull request by gregobad**
Hi Kyle - I made some modifications to your package that allow for the use of the fixest multiple lhs syntax (i.e. writing formulas like c(y1, y2) ~ x1 | z). I also changed the implementation to use data.table rather than base data frames, which should speed things up for larger data sets. Haven't done extensive testing but I match your result on the castle data set. Here's the output:

`did_imputation(data = castle, yname = "c(l_homicide, l_assault)", gname = "effyear",
                                    first_stage = ~ 0 | sid + year,
                                    tname = "year", idname = "sid")`

>     lhs  term   estimate  std.error    conf.low conf.high
> 1: l_homicide treat 0.07980155 0.05312939 -0.02433205 0.1839351
> 2: l_assault treat 0.04955260 0.04596507 -0.04053894 0.1396441

### CODE REVIEW

**Comment by kylebutts** [comment]
Hi Greg,

I'll give this a look over in the next few days. I'll write back after that, but sounds fine to me, thanks for contributing

**Comment by kylebutts** [comment]
Overall, is there an advantage to using the `fixest` `"c(y1, y2)"` notation over `c("y1", "y2")` and then creating that formula? I think that looks a bit cleaner.

I'll go through the code and do a little cleanup (e.g. I will probably use base R `regex` functions even though they're a pain since `stringr` brings with it a bunch of dependencies)

**Comment by gregobad** [comment]
I also realized this and fixed it in some additional commits after making
the pull request. Should I make a new request? Or did you already solve
this?

**Comment by gregobad** [comment]
Also the copy step is somewhat important, data.table modifies by reference
and will otherwise make changes to the data passed to the function (which
users may not expect).

**Comment by kylebutts** [comment]
Sorry for the delay! I finally ran some tests and (to my surprise) multiple y variables are faster than running them separately (about 2x, so I'm assuming the demeaning occurs simultaneously for the `y`s). If they were not, I probably would have said that for maintainability reasons, I wouldn't add the changes. But, alas I stand corrected! 

I'll merge now!

**Pull request merged**
