### PR TITLE
Update code.cpp

### PR DESCRIPTION
**Pull request by zachporreca**
The ARMA_64BIT_WORD issue.

### CODE REVIEW

**Comment by kylebutts** [comment]
Oh crud, yeah it's:
```cpp
#define ARMA_64BIT_WORD  1
```

Did that end up working for you?

**Comment by zachporreca** [comment]
Unfortunately, no. Still no dice and same error. Each change, I have been uninstalling the package on my end and reinstalling from Github (under my branch)... Is that adequate for compiling the C stuff?

**Comment by kylebutts** [comment]
yeah that should do it. Why don't you email me the data and what you're trying to run and I'll see if I can get it to work for you

**Comment by zachporreca** [comment]
Thanks a ton dude, I just sent it over

**Pull request closed without merging**
